services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note_backend
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DEV: "false"
      SERVER_PORT: 5099
      NOTE_APP_JDBC_DB_URL: ${NOTE_APP_JDBC_DB_URL}
      NOTE_APP_JDBC_DB_USER: ${NOTE_APP_JDBC_DB_USER}
      NOTE_APP_JDBC_DB_PASSWORD: ${NOTE_APP_JDBC_DB_PASSWORD}
      SITES_CONFIGURATION_CREDENTIALS: /app/configs/sites/credentials.json
    volumes:
      - ./docs:/app/docs
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ${USER_PROFILE}/configs/sites:/app/configs/sites:ro
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: note_nginx
    network_mode: host
    depends_on:
      - backend
    restart: unless-stopped
